//
// Created by zajhe on 2021/12/17.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_DynamicRegiste */



#define JNI_REG_CLASS "com/example/ndk/DynamicRegiste"

/*
 * Class:     com_example_ndk_DynamicRegiste
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL getHello
        (JNIEnv *env, jobject) {
    return env->NewStringUTF("dynamic regist");
}


/*
 * Class:     com_example_ndk_DynamicRegiste
 * Method:    meaningOfTheUniverse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL meaningOfTheUniverse
        (JNIEnv *env, jobject) {
    return 42;
}

static JNINativeMethod g_methods[] = {
        {"getHello",             "()Ljava/lang/String;", (void *) getHello},
        {"meaningOfTheUniverse", "()I",                  (void *) meaningOfTheUniverse}
};

JNIEXPORT int JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env;
    if (vm->GetEnv((void **) &env, JNI_VERSION_1_6) != JNI_OK) {
        return JNI_ERR;
    }

    jclass javaClass = env->FindClass(JNI_REG_CLASS);
    if (javaClass == NULL) {
        return JNI_ERR;
    }

    int method_count = sizeof(g_methods) / sizeof(g_methods[0]);
    if (env->RegisterNatives(javaClass, g_methods, method_count) < 0) {
        return JNI_ERR;
    }

    return JNI_VERSION_1_6;
}




